name: test-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - dask
  - distributed
  - pandas
  - pyarrow
  - pytest
  - google-cloud-bigquery>=2.11.0
  - google-cloud-bigquery-storage
